# Generated by Django 5.0 on 2023-12-10 07:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translater', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
