# Generated by Django 5.0 on 2023-12-10 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translater', '0002_alter_test_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('teacher', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='group',
            field=models.ForeignKey(default='unknown teacher', on_delete=django.db.models.deletion.CASCADE, to='translater.group'),
            preserve_default=False,
        ),
    ]
